spring:
  application:
    name: Library
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog.xml